[WIP] added pxe_nic support for idrac-redfish
cdearborn/ironic pull request #12
Opened 2020-01-31 11:58 UTC by mahendraKamble

Hi Chris,

I have raised PR for PXE_NIC support for redfish as per your request. 

also, I attached the manager.py(sushy_oem_idrac/resources/manager/manager.py) file. 

In manager.py file, I have written ``export_system_configuration`` method for exporting system configuration where we can specify the target and written property method for getting URI i.e ``export_system_configuration_uri`` 

[manager.zip](https://github.com/cdearborn/ironic/files/4139129/manager.zip)

2020-02-20 22:23 UTC, cdearborn commented on ironic/drivers/modules/drac/inspect.py
> +                              ch.text == 'PXE']
Can we be a little more discriminate when looking for PXE enabled ports above?  We should be looking for an attribute with a Name of LegacyBootProto, and then checking to see if it is set to PXE or not.  And there should be only 1 of these in a given child, so there should be no need to make an array of them.

2020-02-20 22:39 UTC, cdearborn requested changes
I would like to see us be a little more careful when looking for NICs with LegacyBootProto set to PXE.  Other than that, it looks good!

2020-02-21 19:22 UTC, cdearborn requested changes
Thanks for the change.  Can you look at searching for LegacyBootProto when the server is in BIOS mode, and get its value?

2020-02-26 16:50 UTC, mahendraKamble commented
Added check for an attribute with a Name of LegacyBootProto

2020-03-16 21:26 UTC, cdearborn commented
Closing this PR since this code has been submitted upstream:
https://review.opendev.org/693328

2020-03-16 21:26 UTC, closed without merging